import { useState, useEffect } from "react";
import { VoipLayout } from "@/components/voip/layout/VoipLayout";
import { useVoipApi } from "@/hooks/useVoipApi";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Users, DollarSign, TrendingUp, Clock, Loader2 } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

interface DashboardStats {
  totalClients: number;
  activeClients: number;
  totalRevenue: number;
  lifetimeCommission: number;
  thisMonthCommission: number;
  pendingPayouts: number;
}

export default function PartnerDashboard() {
  const { apiCall } = useVoipApi();
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      const result = await apiCall<DashboardStats>("voip-partner", {
        params: { action: "dashboard" },
      });
      if (result.data) setStats(result.data);
      setLoading(false);
    };
    fetchStats();
  }, [apiCall]);

  if (loading) {
    return (
      <VoipLayout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </VoipLayout>
    );
  }

  const statCards = [
    { label: "Total Clients", value: stats?.totalClients || 0, icon: Users, color: "text-blue-500" },
    { label: "Active Clients", value: stats?.activeClients || 0, icon: Users, color: "text-green-500" },
    { label: "Total Revenue", value: `$${(stats?.totalRevenue || 0).toFixed(2)}`, icon: DollarSign, color: "text-primary" },
    { label: "Lifetime Commission", value: `$${(stats?.lifetimeCommission || 0).toFixed(2)}`, icon: TrendingUp, color: "text-emerald-500" },
    { label: "This Month", value: `$${(stats?.thisMonthCommission || 0).toFixed(2)}`, icon: TrendingUp, color: "text-amber-500" },
    { label: "Pending Payouts", value: `$${(stats?.pendingPayouts || 0).toFixed(2)}`, icon: Clock, color: "text-orange-500" },
  ];

  return (
    <VoipLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Partner Dashboard</h1>
          <p className="text-muted-foreground">Overview of your referrals and earnings</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {statCards.map((stat) => {
            const Icon = stat.icon;
            return (
              <Card key={stat.label}>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium text-muted-foreground">{stat.label}</CardTitle>
                  <Icon className={`w-4 h-4 ${stat.color}`} />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{stat.value}</div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Quick Actions</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <Link to="/voip/partner/clients">
                <Button variant="outline" className="w-full justify-start">
                  <Users className="w-4 h-4 mr-2" />
                  View My Clients
                </Button>
              </Link>
              <Link to="/voip/partner/earnings">
                <Button variant="outline" className="w-full justify-start">
                  <DollarSign className="w-4 h-4 mr-2" />
                  View Earnings
                </Button>
              </Link>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Commission Info</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                You earn <span className="font-semibold text-foreground">5%</span> commission on every revenue event generated by your referred clients.
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                Commissions are tracked automatically and paid out by the admin team.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </VoipLayout>
  );
}
